//! Integration tests for `schema.sql` manifest.

mod common;

use predicates::prelude::*;
use rusqlite::Connection;
use tempfile::TempDir;

use common::{stig_cmd, write_migration};

/// Query the number of rows in `schema_migrations` from the project DB.
fn count_schema_migrations(dir: &TempDir) -> i64 {
    let db_path = dir.path().join("app.db");
    let conn = Connection::open(db_path).unwrap();
    conn.query_row("SELECT COUNT(*) FROM schema_migrations", [], |r| r.get(0))
        .unwrap()
}

/// Check whether a table exists in the project DB.
fn table_exists(dir: &TempDir, name: &str) -> bool {
    let db_path = dir.path().join("app.db");
    let conn = Connection::open(db_path).unwrap();
    let count: i64 = conn
        .query_row(
            "SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name=?1",
            [name],
            |r| r.get(0),
        )
        .unwrap();
    count > 0
}

/// Read the schema.sql content.
fn read_schema_sql(dir: &TempDir) -> String {
    std::fs::read_to_string(dir.path().join("db/schema.sql")).unwrap()
}

// `stig init` creates schema.sql with header comment
#[test]
fn init_creates_schema_sql() {
    let dir = TempDir::new().unwrap();
    stig_cmd(&dir).arg("init").assert().success();

    let schema_path = dir.path().join("db/schema.sql");
    assert!(schema_path.exists(), "schema.sql should be created by init");

    let content = std::fs::read_to_string(&schema_path).unwrap();
    assert!(content.contains("-- stig schema manifest"));
    assert!(content.contains("-- Generated by `stig migrate`. Do not edit by hand."));
}

// `stig migrate` on fresh DB with populated schema.sql uses manifest fast path
#[test]
fn migrate_fresh_db_uses_schema_manifest() {
    let dir = TempDir::new().unwrap();
    stig_cmd(&dir).arg("init").assert().success();

    write_migration(
        &dir,
        "20240101000000",
        "create_users",
        "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);",
    );
    write_migration(
        &dir,
        "20240102000000",
        "create_posts",
        "CREATE TABLE posts (id INTEGER PRIMARY KEY, title TEXT);",
    );

    // First migrate: applies individually, generates schema.sql
    stig_cmd(&dir).arg("migrate").assert().success();
    assert!(table_exists(&dir, "users"));
    assert!(table_exists(&dir, "posts"));
    assert_eq!(count_schema_migrations(&dir), 2);

    let schema_content = read_schema_sql(&dir);
    assert!(schema_content.contains("CREATE TABLE users"));
    assert!(schema_content.contains("CREATE TABLE posts"));

    // Delete the DB but keep schema.sql
    std::fs::remove_file(dir.path().join("app.db")).unwrap();

    // Second migrate: should use schema manifest fast path
    stig_cmd(&dir)
        .arg("migrate")
        .assert()
        .success()
        .stdout(predicate::str::contains("applied db/schema.sql"))
        .stdout(predicate::str::contains("2 migrations marked as applied"));

    assert!(table_exists(&dir, "users"));
    assert!(table_exists(&dir, "posts"));
    assert_eq!(count_schema_migrations(&dir), 2);
}

// `stig migrate` regenerates schema.sql after full migration
#[test]
fn migrate_generates_schema_after_full_migrate() {
    let dir = TempDir::new().unwrap();
    stig_cmd(&dir).arg("init").assert().success();

    write_migration(
        &dir,
        "20240101000000",
        "create_users",
        "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);",
    );
    write_migration(
        &dir,
        "20240102000000",
        "create_posts",
        "CREATE TABLE posts (id INTEGER PRIMARY KEY, title TEXT, user_id INTEGER);",
    );

    stig_cmd(&dir).arg("migrate").assert().success();

    let schema_content = read_schema_sql(&dir);
    assert!(schema_content.contains("CREATE TABLE users"));
    assert!(schema_content.contains("CREATE TABLE posts"));
    // Should have semicolons
    assert!(schema_content.contains("CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);"));
    assert!(
        schema_content
            .contains("CREATE TABLE posts (id INTEGER PRIMARY KEY, title TEXT, user_id INTEGER);")
    );
}

// `stig reset` uses schema manifest when available
#[test]
fn reset_uses_schema_manifest() {
    let dir = TempDir::new().unwrap();
    stig_cmd(&dir).arg("init").assert().success();

    write_migration(
        &dir,
        "20240101000000",
        "create_users",
        "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);",
    );
    write_migration(
        &dir,
        "20240102000000",
        "create_posts",
        "CREATE TABLE posts (id INTEGER PRIMARY KEY, title TEXT);",
    );

    stig_cmd(&dir).arg("migrate").assert().success();

    // Insert data that should be lost
    let db_path = dir.path().join("app.db");
    {
        let conn = Connection::open(&db_path).unwrap();
        conn.execute("INSERT INTO users (name) VALUES ('test')", [])
            .unwrap();
    }

    // Reset should use schema manifest fast path
    stig_cmd(&dir)
        .arg("reset")
        .arg("--yes")
        .assert()
        .success()
        .stdout(predicate::str::contains("applied db/schema.sql"))
        .stdout(predicate::str::contains("2 migrations marked as applied"));

    assert!(table_exists(&dir, "users"));
    assert!(table_exists(&dir, "posts"));
    assert_eq!(count_schema_migrations(&dir), 2);

    // Data is gone
    let conn = Connection::open(&db_path).unwrap();
    let count: i64 = conn
        .query_row("SELECT COUNT(*) FROM users", [], |r| r.get(0))
        .unwrap();
    assert_eq!(count, 0);
}

// `stig reset` falls back to replay when no schema manifest
#[test]
fn reset_falls_back_without_schema() {
    let dir = TempDir::new().unwrap();
    stig_cmd(&dir).arg("init").assert().success();

    write_migration(
        &dir,
        "20240101000000",
        "create_users",
        "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);",
    );

    stig_cmd(&dir).arg("migrate").assert().success();

    // Delete schema.sql to force fallback
    std::fs::remove_file(dir.path().join("db/schema.sql")).unwrap();

    // Reset should fall back to replay
    stig_cmd(&dir)
        .arg("reset")
        .arg("--yes")
        .assert()
        .success()
        .stdout(predicate::str::contains("✓ reset complete"))
        .stdout(predicate::str::contains("applied db/schema.sql").not());

    assert!(table_exists(&dir, "users"));
    assert_eq!(count_schema_migrations(&dir), 1);
}

// Incremental migration regenerates schema.sql when fully migrated
#[test]
fn migrate_incremental_regenerates_schema() {
    let dir = TempDir::new().unwrap();
    stig_cmd(&dir).arg("init").assert().success();

    // First migration
    write_migration(
        &dir,
        "20240101000000",
        "create_users",
        "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);",
    );
    stig_cmd(&dir).arg("migrate").assert().success();

    let schema_after_first = read_schema_sql(&dir);
    assert!(schema_after_first.contains("CREATE TABLE users"));
    assert!(!schema_after_first.contains("CREATE TABLE posts"));

    // Second migration
    write_migration(
        &dir,
        "20240102000000",
        "create_posts",
        "CREATE TABLE posts (id INTEGER PRIMARY KEY, title TEXT);",
    );
    stig_cmd(&dir).arg("migrate").assert().success();

    let schema_after_second = read_schema_sql(&dir);
    assert!(schema_after_second.contains("CREATE TABLE users"));
    assert!(schema_after_second.contains("CREATE TABLE posts"));
}

// Custom schema path via env var
#[test]
fn schema_path_env_override() {
    let dir = TempDir::new().unwrap();
    stig_cmd(&dir).arg("init").assert().success();

    write_migration(
        &dir,
        "20240101000000",
        "create_users",
        "CREATE TABLE users (id INTEGER PRIMARY KEY);",
    );

    // Use custom schema path
    stig_cmd(&dir)
        .env("STIG_SCHEMA_PATH", "custom/my_schema.sql")
        .arg("migrate")
        .assert()
        .success();

    // Schema should be at custom path
    let custom_path = dir.path().join("custom/my_schema.sql");
    assert!(custom_path.exists());
    let content = std::fs::read_to_string(&custom_path).unwrap();
    assert!(content.contains("CREATE TABLE users"));

    // Default path should still be header-only (from init)
    let default_path = dir.path().join("db/schema.sql");
    let default_content = std::fs::read_to_string(&default_path).unwrap();
    assert!(!default_content.contains("CREATE TABLE"));
}
