//! Schema manifest (`schema.sql`) generation and application.
//!
//! The schema manifest is a rolled-up SQL file that represents the final state
//! of applying all migrations to a fresh database. It enables fast bootstrap
//! of fresh databases without replaying every migration individually.

use std::path::PathBuf;

use anyhow::{Context, Result};
use rusqlite::{Connection, params};

use crate::config::Config;
use crate::db::Db;
use crate::migrate::discover::MigrationFile;
use crate::sha256_hex;

const HEADER: &str =
    "-- stig schema manifest\n-- Generated by `stig migrate`. Do not edit by hand.\n";

/// Resolve the absolute path to the schema manifest file.
pub fn schema_path(config: &Config) -> PathBuf {
    config.resolve_path(&config.schema_path)
}

/// Check whether the schema manifest file exists on disk.
pub fn schema_exists(config: &Config) -> bool {
    schema_path(config).is_file()
}

/// Check whether the schema manifest has actual DDL content (not just the header).
pub fn schema_has_content(config: &Config) -> bool {
    match load_schema_sql(config) {
        Ok(Some(sql)) => {
            let stripped = sql
                .lines()
                .filter(|line| !line.trim().is_empty() && !line.trim().starts_with("--"))
                .collect::<String>();
            !stripped.is_empty()
        }
        _ => false,
    }
}

/// Read the schema manifest file if it exists.
///
/// Returns `Ok(None)` if the file does not exist.
pub fn load_schema_sql(config: &Config) -> Result<Option<String>> {
    let path = schema_path(config);
    if !path.is_file() {
        return Ok(None);
    }
    std::fs::read_to_string(&path)
        .with_context(|| format!("failed to read schema manifest: {}", path.display()))
        .map(Some)
}

/// Write the schema manifest file with the standard header comment.
pub fn write_schema_sql(config: &Config, sql: &str) -> Result<()> {
    let path = schema_path(config);

    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("failed to create directory: {}", parent.display()))?;
    }

    let content = if sql.is_empty() {
        HEADER.to_string()
    } else {
        format!("{HEADER}\n{sql}")
    };

    std::fs::write(&path, content)
        .with_context(|| format!("failed to write schema manifest: {}", path.display()))
}

/// Generate the schema SQL by querying `sqlite_master` for all DDL statements.
///
/// Excludes internal SQLite objects (`sqlite_%`) and the `schema_migrations`
/// tracking table. Returns statements ordered by `type`, then `name` for
/// deterministic output. Each statement is terminated with a semicolon.
pub fn generate_schema_sql(conn: &Connection) -> Result<String> {
    let mut stmt = conn
        .prepare(
            "SELECT sql FROM sqlite_master \
             WHERE sql IS NOT NULL \
               AND type IN ('table', 'index', 'trigger', 'view') \
               AND name NOT LIKE 'sqlite_%' \
               AND name != 'schema_migrations' \
             ORDER BY type, name",
        )
        .context("failed to prepare schema query")?;

    let mut statements: Vec<String> = stmt
        .query_map([], |row| row.get(0))
        .context("failed to query sqlite_master")?
        .filter_map(|r| r.ok())
        .collect();

    statements.retain(|s| !s.trim().is_empty());
    statements.dedup();

    let with_semicolons: Vec<String> = statements
        .into_iter()
        .map(|s| {
            let trimmed = s.trim_end();
            if trimmed.ends_with(';') {
                trimmed.to_string()
            } else {
                format!("{trimmed};")
            }
        })
        .collect();

    Ok(with_semicolons.join("\n\n"))
}

/// Apply the schema manifest to a fresh database.
///
/// Executes the schema SQL, then populates `schema_migrations` with all known
/// migration versions and their checksums. Returns the number of migrations
/// marked as applied.
pub fn apply_schema_manifest(db: &Db, config: &Config, files: &[MigrationFile]) -> Result<usize> {
    let sql = load_schema_sql(config)?.unwrap_or_default();

    if !sql.is_empty() {
        db.connection()
            .execute_batch(&sql)
            .context("failed to execute schema manifest")?;
    }

    let mut count = 0;
    for file in files {
        let version = file.version();
        let content = std::fs::read_to_string(&file.path)
            .with_context(|| format!("failed to read migration file: {}", file.path.display()))?;
        let checksum = sha256_hex(content.as_bytes());

        db.connection()
            .execute(
                "INSERT INTO schema_migrations (version, checksum) VALUES (?1, ?2)",
                params![version, checksum],
            )
            .with_context(|| format!("failed to record {version} in schema_migrations"))?;

        count += 1;
    }

    Ok(count)
}

#[cfg(test)]
mod tests {
    use super::*;
    use rusqlite::Connection;
    use tempfile::TempDir;

    fn setup_db() -> Connection {
        let conn = Connection::open_in_memory().unwrap();
        conn.execute_batch(
            "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT NOT NULL);
             CREATE TABLE posts (id INTEGER PRIMARY KEY, title TEXT, user_id INTEGER, FOREIGN KEY(user_id) REFERENCES users(id));
             CREATE INDEX idx_posts_user_id ON posts(user_id);",
        )
        .unwrap();
        conn
    }

    #[test]
    fn generate_schema_sql_returns_all_ddl() {
        let conn = setup_db();
        let sql = generate_schema_sql(&conn).unwrap();

        assert!(sql.contains("CREATE TABLE users"));
        assert!(sql.contains("CREATE TABLE posts"));
        assert!(sql.contains("CREATE INDEX idx_posts_user_id"));
    }

    #[test]
    fn generate_schema_sql_excludes_schema_migrations() {
        let conn = setup_db();
        conn.execute_batch(
            "CREATE TABLE schema_migrations (version TEXT PRIMARY KEY, checksum TEXT NOT NULL);",
        )
        .unwrap();

        let sql = generate_schema_sql(&conn).unwrap();
        assert!(
            !sql.contains("schema_migrations"),
            "schema_migrations should be excluded"
        );
    }

    #[test]
    fn generate_schema_sql_excludes_sqlite_internal() {
        let conn = setup_db();
        let sql = generate_schema_sql(&conn).unwrap();
        assert!(
            !sql.contains("sqlite_"),
            "internal SQLite objects should be excluded"
        );
    }

    #[test]
    fn generate_schema_sql_empty_database() {
        let conn = Connection::open_in_memory().unwrap();
        let sql = generate_schema_sql(&conn).unwrap();
        assert!(sql.is_empty());
    }

    #[test]
    fn write_and_load_round_trip() {
        let dir = TempDir::new().unwrap();
        let config = Config {
            project_root: dir.path().to_path_buf(),
            schema_path: "db/schema.sql".to_string(),
            ..Config::default()
        };

        let sql = "CREATE TABLE test (id INTEGER);";
        write_schema_sql(&config, sql).unwrap();

        let loaded = load_schema_sql(&config).unwrap().unwrap();
        assert!(loaded.starts_with(HEADER));
        assert!(loaded.contains("CREATE TABLE test"));
    }

    #[test]
    fn load_schema_sql_returns_none_when_missing() {
        let dir = TempDir::new().unwrap();
        let config = Config {
            project_root: dir.path().to_path_buf(),
            schema_path: "db/schema.sql".to_string(),
            ..Config::default()
        };

        assert!(load_schema_sql(&config).unwrap().is_none());
    }

    #[test]
    fn schema_exists_returns_false_when_missing() {
        let dir = TempDir::new().unwrap();
        let config = Config {
            project_root: dir.path().to_path_buf(),
            schema_path: "db/schema.sql".to_string(),
            ..Config::default()
        };

        assert!(!schema_exists(&config));
    }

    #[test]
    fn schema_exists_returns_true_when_present() {
        let dir = TempDir::new().unwrap();
        let config = Config {
            project_root: dir.path().to_path_buf(),
            schema_path: "db/schema.sql".to_string(),
            ..Config::default()
        };

        write_schema_sql(&config, "SELECT 1;").unwrap();
        assert!(schema_exists(&config));
    }

    #[test]
    fn write_schema_sql_creates_parent_directory() {
        let dir = TempDir::new().unwrap();
        let config = Config {
            project_root: dir.path().to_path_buf(),
            schema_path: "deep/nested/dir/schema.sql".to_string(),
            ..Config::default()
        };

        write_schema_sql(&config, "SELECT 1;").unwrap();
        assert!(schema_exists(&config));
    }

    #[test]
    fn write_schema_sql_empty_sql_writes_header_only() {
        let dir = TempDir::new().unwrap();
        let config = Config {
            project_root: dir.path().to_path_buf(),
            schema_path: "db/schema.sql".to_string(),
            ..Config::default()
        };

        write_schema_sql(&config, "").unwrap();
        let loaded = load_schema_sql(&config).unwrap().unwrap();
        assert_eq!(loaded, HEADER);
    }
}
