//! Schema manifest (`schema.sql`) generation and application.
//!
//! The schema manifest is a rolled-up SQL file that represents the final state
//! of applying all migrations to a fresh database. It enables fast bootstrap
//! of fresh databases without replaying every migration individually.

use std::path::PathBuf;

use anyhow::{Context, Result};
use rusqlite::{Connection, params};
use sqlparser::dialect::SQLiteDialect;
use sqlparser::parser::Parser;

use crate::config::Config;
use crate::db::Db;
use crate::migrate::discover::MigrationFile;
use crate::sha256_hex;

const HEADER: &str =
    "-- stig schema manifest\n-- Generated by `stig migrate`. Do not edit by hand.\n";

/// Resolve the absolute path to the schema manifest file.
pub fn schema_path(config: &Config) -> PathBuf {
    config.resolve_path(&config.schema_path)
}

/// Check whether the schema manifest file exists on disk.
pub fn schema_exists(config: &Config) -> bool {
    schema_path(config).is_file()
}

/// Check whether the schema manifest has actual DDL content (not just the header).
///
/// Uses `sqlparser` to parse the file and checks whether any statements remain
/// after stripping the standard header comment. This correctly handles both
/// `--` line comments and `/* */` block comments.
pub fn schema_has_content(config: &Config) -> bool {
    match load_schema_sql(config) {
        Ok(Some(sql)) => {
            let stripped = strip_header(&sql);
            Parser::parse_sql(&SQLiteDialect {}, &stripped)
                .map(|stmts| !stmts.is_empty())
                .unwrap_or(false)
        }
        _ => false,
    }
}

/// Strip the standard header comment from schema SQL content.
fn strip_header(sql: &str) -> String {
    let mut result = sql.to_string();
    for line in HEADER.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() {
            continue;
        }
        if let Some(pos) = result.find(trimmed) {
            result.replace_range(pos..pos + line.len(), "");
        }
    }
    result
}

/// Read the schema manifest file if it exists.
///
/// Returns `Ok(None)` if the file does not exist.
pub fn load_schema_sql(config: &Config) -> Result<Option<String>> {
    let path = schema_path(config);
    if !path.is_file() {
        return Ok(None);
    }
    std::fs::read_to_string(&path)
        .with_context(|| format!("failed to read schema manifest: {}", path.display()))
        .map(Some)
}

/// Write the schema manifest file with the standard header comment.
pub fn write_schema_sql(config: &Config, sql: &str) -> Result<()> {
    let path = schema_path(config);

    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("failed to create directory: {}", parent.display()))?;
    }

    let content = if sql.is_empty() {
        HEADER.to_string()
    } else {
        format!("{HEADER}\n{sql}")
    };

    std::fs::write(&path, content)
        .with_context(|| format!("failed to write schema manifest: {}", path.display()))
}

/// Generate the schema SQL by querying `sqlite_master` for all DDL statements.
///
/// Excludes internal SQLite objects (`sqlite_%`) and the `schema_migrations`
/// tracking table. Returns statements in dependency-safe order: tables first,
/// then views, then indexes, then triggers. Each statement is terminated with
/// a semicolon.
pub fn generate_schema_sql(conn: &Connection) -> Result<String> {
    let mut stmt = conn
        .prepare(
            "SELECT sql FROM sqlite_master \
             WHERE sql IS NOT NULL \
               AND type IN ('table', 'index', 'trigger', 'view') \
               AND name NOT LIKE 'sqlite_%' \
               AND name != 'schema_migrations' \
             ORDER BY \
               CASE type \
                 WHEN 'table'   THEN 1 \
                 WHEN 'view'    THEN 2 \
                 WHEN 'index'   THEN 3 \
                 WHEN 'trigger' THEN 4 \
                 ELSE 5 \
               END, \
               name",
        )
        .context("failed to prepare schema query")?;

    let rows = stmt
        .query_map([], |row| row.get(0))
        .context("failed to query sqlite_master")?;

    let mut statements: Vec<String> = rows
        .collect::<std::result::Result<Vec<_>, _>>()
        .context("failed to read schema rows")?;

    statements.retain(|s| !s.trim().is_empty());
    statements.dedup();

    let with_semicolons: Vec<String> = statements
        .into_iter()
        .map(|s| {
            let trimmed = s.trim_end();
            if trimmed.ends_with(';') {
                trimmed.to_string()
            } else {
                format!("{trimmed};")
            }
        })
        .collect();

    Ok(with_semicolons.join("\n\n"))
}

/// Apply the schema manifest to a fresh database.
///
/// Executes the schema SQL, then populates `schema_migrations` with all known
/// migration versions and their checksums. The entire operation is wrapped in
/// an explicit transaction so that partial failures leave the database
/// unchanged. Returns the number of migrations marked as applied.
///
/// # Errors
///
/// Returns an error if the manifest file is missing or contains no DDL
/// content (header-only).
pub fn apply_schema_manifest(db: &Db, config: &Config, files: &[MigrationFile]) -> Result<usize> {
    let sql = load_schema_sql(config)?.ok_or_else(|| {
        anyhow::anyhow!(
            "schema manifest not found: {}",
            schema_path(config).display()
        )
    })?;

    let stripped = strip_header(&sql);
    let stmts = Parser::parse_sql(&SQLiteDialect {}, &stripped).with_context(|| {
        format!(
            "failed to parse schema manifest: {}",
            schema_path(config).display()
        )
    })?;

    if stmts.is_empty() {
        return Err(anyhow::anyhow!(
            "schema manifest has no DDL content: {}",
            schema_path(config).display()
        ));
    }

    let conn = db.connection();
    conn.execute_batch("BEGIN")
        .context("failed to begin transaction")?;

    if let Err(e) = conn.execute_batch(&sql) {
        let _ = conn.execute_batch("ROLLBACK");
        return Err(e).context("failed to execute schema manifest");
    }

    let mut count = 0;
    for file in files {
        let version = file.version();
        let content = std::fs::read_to_string(&file.path)
            .with_context(|| format!("failed to read migration file: {}", file.path.display()))?;
        let checksum = sha256_hex(content.as_bytes());

        if let Err(e) = conn.execute(
            "INSERT INTO schema_migrations (version, checksum) VALUES (?1, ?2)",
            params![version, checksum],
        ) {
            let _ = conn.execute_batch("ROLLBACK");
            return Err(e)
                .with_context(|| format!("failed to record {version} in schema_migrations"));
        }

        count += 1;
    }

    conn.execute_batch("COMMIT")
        .context("failed to commit schema manifest transaction")?;

    Ok(count)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::db::Db;
    use rusqlite::Connection;
    use tempfile::TempDir;

    fn setup_db() -> Connection {
        let conn = Connection::open_in_memory().unwrap();
        conn.execute_batch(
            "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT NOT NULL);
             CREATE TABLE posts (id INTEGER PRIMARY KEY, title TEXT, user_id INTEGER, FOREIGN KEY(user_id) REFERENCES users(id));
             CREATE INDEX idx_posts_user_id ON posts(user_id);",
        )
        .unwrap();
        conn
    }

    #[test]
    fn generate_schema_sql_returns_all_ddl() {
        let conn = setup_db();
        let sql = generate_schema_sql(&conn).unwrap();

        assert!(sql.contains("CREATE TABLE users"));
        assert!(sql.contains("CREATE TABLE posts"));
        assert!(sql.contains("CREATE INDEX idx_posts_user_id"));
    }

    #[test]
    fn generate_schema_sql_excludes_schema_migrations() {
        let conn = setup_db();
        conn.execute_batch(
            "CREATE TABLE schema_migrations (version TEXT PRIMARY KEY, checksum TEXT NOT NULL);",
        )
        .unwrap();

        let sql = generate_schema_sql(&conn).unwrap();
        assert!(
            !sql.contains("schema_migrations"),
            "schema_migrations should be excluded"
        );
    }

    #[test]
    fn generate_schema_sql_excludes_sqlite_internal() {
        let conn = setup_db();
        let sql = generate_schema_sql(&conn).unwrap();
        assert!(
            !sql.contains("sqlite_"),
            "internal SQLite objects should be excluded"
        );
    }

    #[test]
    fn generate_schema_sql_empty_database() {
        let conn = Connection::open_in_memory().unwrap();
        let sql = generate_schema_sql(&conn).unwrap();
        assert!(sql.is_empty());
    }

    #[test]
    fn generate_schema_sql_tables_before_indexes() {
        let conn = setup_db();
        let sql = generate_schema_sql(&conn).unwrap();

        let table_pos = sql.find("CREATE TABLE users").unwrap();
        let index_pos = sql.find("CREATE INDEX idx_posts_user_id").unwrap();
        assert!(
            table_pos < index_pos,
            "tables must appear before indexes in generated schema"
        );
    }

    #[test]
    fn apply_schema_manifest_fails_when_missing() {
        let dir = TempDir::new().unwrap();
        let config = Config {
            project_root: dir.path().to_path_buf(),
            schema_path: "db/schema.sql".to_string(),
            database_path: ":memory:".to_string(),
            ..Config::default()
        };

        let db = Db::open(&config).unwrap();

        let result = apply_schema_manifest(&db, &config, &[]);
        assert!(result.is_err());
        let err = result.unwrap_err().to_string();
        assert!(err.contains("not found"));
    }

    #[test]
    fn apply_schema_manifest_fails_when_header_only() {
        let dir = TempDir::new().unwrap();
        let config = Config {
            project_root: dir.path().to_path_buf(),
            schema_path: "db/schema.sql".to_string(),
            database_path: ":memory:".to_string(),
            ..Config::default()
        };

        write_schema_sql(&config, "").unwrap();

        let db = Db::open(&config).unwrap();

        let result = apply_schema_manifest(&db, &config, &[]);
        assert!(result.is_err());
        let err = result.unwrap_err().to_string();
        assert!(err.contains("no DDL content"));
    }

    #[test]
    fn schema_has_content_false_for_block_comments_only() {
        let dir = TempDir::new().unwrap();
        let config = Config {
            project_root: dir.path().to_path_buf(),
            schema_path: "db/schema.sql".to_string(),
            ..Config::default()
        };

        std::fs::create_dir_all(dir.path().join("db")).unwrap();
        let content = format!("{}\n/* some block comment */\n/* another */\n", HEADER);
        std::fs::write(schema_path(&config), content).unwrap();

        assert!(!schema_has_content(&config));
    }

    #[test]
    fn schema_has_content_true_for_actual_ddl() {
        let dir = TempDir::new().unwrap();
        let config = Config {
            project_root: dir.path().to_path_buf(),
            schema_path: "db/schema.sql".to_string(),
            ..Config::default()
        };

        std::fs::create_dir_all(dir.path().join("db")).unwrap();
        let content = format!("{}\nCREATE TABLE foo (id INTEGER);\n", HEADER);
        std::fs::write(schema_path(&config), content).unwrap();

        assert!(schema_has_content(&config));
    }

    #[test]
    fn write_and_load_round_trip() {
        let dir = TempDir::new().unwrap();
        let config = Config {
            project_root: dir.path().to_path_buf(),
            schema_path: "db/schema.sql".to_string(),
            ..Config::default()
        };

        let sql = "CREATE TABLE test (id INTEGER);";
        write_schema_sql(&config, sql).unwrap();

        let loaded = load_schema_sql(&config).unwrap().unwrap();
        assert!(loaded.starts_with(HEADER));
        assert!(loaded.contains("CREATE TABLE test"));
    }

    #[test]
    fn load_schema_sql_returns_none_when_missing() {
        let dir = TempDir::new().unwrap();
        let config = Config {
            project_root: dir.path().to_path_buf(),
            schema_path: "db/schema.sql".to_string(),
            ..Config::default()
        };

        assert!(load_schema_sql(&config).unwrap().is_none());
    }

    #[test]
    fn schema_exists_returns_false_when_missing() {
        let dir = TempDir::new().unwrap();
        let config = Config {
            project_root: dir.path().to_path_buf(),
            schema_path: "db/schema.sql".to_string(),
            ..Config::default()
        };

        assert!(!schema_exists(&config));
    }

    #[test]
    fn schema_exists_returns_true_when_present() {
        let dir = TempDir::new().unwrap();
        let config = Config {
            project_root: dir.path().to_path_buf(),
            schema_path: "db/schema.sql".to_string(),
            ..Config::default()
        };

        write_schema_sql(&config, "SELECT 1;").unwrap();
        assert!(schema_exists(&config));
    }

    #[test]
    fn write_schema_sql_creates_parent_directory() {
        let dir = TempDir::new().unwrap();
        let config = Config {
            project_root: dir.path().to_path_buf(),
            schema_path: "deep/nested/dir/schema.sql".to_string(),
            ..Config::default()
        };

        write_schema_sql(&config, "SELECT 1;").unwrap();
        assert!(schema_exists(&config));
    }

    #[test]
    fn write_schema_sql_empty_sql_writes_header_only() {
        let dir = TempDir::new().unwrap();
        let config = Config {
            project_root: dir.path().to_path_buf(),
            schema_path: "db/schema.sql".to_string(),
            ..Config::default()
        };

        write_schema_sql(&config, "").unwrap();
        let loaded = load_schema_sql(&config).unwrap().unwrap();
        assert_eq!(loaded, HEADER);
    }
}
