//! Schema manifest (`schema.sql`) generation and application.
//!
//! The schema manifest is a rolled-up SQL file that represents the final state
//! of applying all migrations to a fresh database. It enables fast bootstrap
//! of fresh databases without replaying every migration individually.

pub mod diff;

use std::path::PathBuf;

use anyhow::{Context, Result};
use rusqlite::Connection;
use sqlparser::dialect::SQLiteDialect;
use sqlparser::parser::Parser;

use tracing::warn;

use crate::config::Config;
use crate::db::Db;
use crate::migrate::discover::MigrationFile;
use crate::sha256_hex;

const HEADER: &str =
    "-- stig schema manifest\n-- Generated by `stig migrate`. Do not edit by hand.\n";

/// Resolve the absolute path to the schema manifest file.
pub fn schema_path(config: &Config) -> PathBuf {
    config.resolve_path(&config.schema_path)
}

/// Check whether the schema manifest file exists on disk.
pub fn schema_exists(config: &Config) -> bool {
    schema_path(config).is_file()
}

/// Check whether the schema manifest has actual DDL content (not just the header).
///
/// Uses `sqlparser` to parse the file and checks whether any schema-creating
/// DDL statements are present (CREATE TABLE, VIEW, INDEX, TRIGGER, or their
/// ALTER variants). Since `sqlparser` already ignores SQL comments, no manual
/// header stripping is needed.
pub fn schema_has_content(config: &Config) -> bool {
    match load_schema_sql(config) {
        Ok(Some(sql)) => Parser::parse_sql(&SQLiteDialect {}, &sql)
            .map(|stmts| stmts.iter().any(is_schema_creating_statement))
            .unwrap_or(false),
        _ => false,
    }
}

/// Check whether a parsed SQL statement creates or alters a schema object.
///
/// Returns `true` for CREATE TABLE/VIEW/INDEX/TRIGGER and ALTER TABLE/VIEW/INDEX
/// statements. Returns `false` for INSERT, SELECT, and other non-DDL statements.
fn is_schema_creating_statement(stmt: &sqlparser::ast::Statement) -> bool {
    use sqlparser::ast::Statement;
    matches!(
        stmt,
        Statement::CreateTable(_)
            | Statement::CreateView(_)
            | Statement::CreateIndex(_)
            | Statement::CreateTrigger(_)
            | Statement::CreateVirtualTable { .. }
            | Statement::AlterTable(_)
            | Statement::AlterView { .. }
            | Statement::AlterIndex { .. }
    )
}

/// Extract the latest migration version embedded in the schema manifest.
///
/// Uses `sqlparser` to parse INSERT statements targeting `schema_migrations`
/// and extracts the version column value. Returns `None` if no matching
/// INSERT statements are found.
pub fn schema_version(config: &Config) -> Result<Option<String>> {
    use sqlparser::ast::{Expr, Statement, TableObject, ValueWithSpan};

    let sql = match load_schema_sql(config)? {
        Some(s) => s,
        None => return Ok(None),
    };

    let stmts = Parser::parse_sql(&SQLiteDialect {}, &sql).with_context(|| {
        format!(
            "failed to parse schema manifest for version extraction: {}",
            schema_path(config).display()
        )
    })?;

    let mut latest: Option<String> = None;
    for stmt in stmts {
        let Statement::Insert(insert) = stmt else {
            continue;
        };

        let TableObject::TableName(table_name) = &insert.table else {
            continue;
        };

        let name_str = table_name
            .0
            .iter()
            .filter_map(|part| part.as_ident())
            .map(|ident| ident.value.as_str())
            .collect::<Vec<_>>()
            .join(".");

        if name_str != "schema_migrations" {
            continue;
        }

        let Some(source) = &insert.source else {
            continue;
        };

        let sqlparser::ast::SetExpr::Values(values) = source.body.as_ref() else {
            continue;
        };

        for row in &values.rows {
            if let Some(Expr::Value(ValueWithSpan {
                value: sqlparser::ast::Value::SingleQuotedString(v),
                ..
            })) = row.content.first()
            {
                latest = Some(match latest {
                    Some(existing) => std::cmp::max(existing, v.clone()),
                    None => v.clone(),
                });
            }
        }
    }

    Ok(latest)
}

/// Check whether the schema manifest is up to date with the current migration files.
///
/// Returns `true` if the manifest's embedded version matches (or is newer than)
/// the latest on-disk migration. Returns `false` if any migration file on disk
/// is newer than what the manifest contains.
pub fn schema_is_fresh(config: &Config, files: &[MigrationFile]) -> bool {
    let manifest_version = match schema_version(config) {
        Ok(Some(v)) => v,
        _ => return false,
    };

    let latest_on_disk = files.iter().map(|f| f.version()).max().unwrap_or_default();

    manifest_version >= latest_on_disk
}

/// Read the schema manifest file if it exists.
///
/// Returns `Ok(None)` if the file does not exist.
pub fn load_schema_sql(config: &Config) -> Result<Option<String>> {
    let path = schema_path(config);
    if !path.is_file() {
        return Ok(None);
    }
    std::fs::read_to_string(&path)
        .with_context(|| format!("failed to read schema manifest: {}", path.display()))
        .map(Some)
}

/// Write the schema manifest file with the standard header comment.
pub fn write_schema_sql(config: &Config, sql: &str) -> Result<()> {
    let path = schema_path(config);

    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("failed to create directory: {}", parent.display()))?;
    }

    let content = if sql.is_empty() {
        HEADER.to_string()
    } else {
        format!("{HEADER}\n{sql}")
    };

    std::fs::write(&path, content)
        .with_context(|| format!("failed to write schema manifest: {}", path.display()))
}

/// Generate the schema SQL by querying `sqlite_master` for all DDL statements.
///
/// Excludes internal SQLite objects (`sqlite_%`) and the `schema_migrations`
/// tracking table. Returns statements in dependency-safe order: tables first,
/// then views, then indexes, then triggers. Each statement is terminated with
/// a semicolon. Appends `INSERT INTO schema_migrations` statements for all
/// applied migrations so the manifest is fully self-contained.
pub fn generate_schema_sql(conn: &Connection, files: &[MigrationFile]) -> Result<String> {
    let mut stmt = conn
        .prepare(
            "SELECT sql FROM sqlite_master \
             WHERE sql IS NOT NULL \
               AND type IN ('table', 'index', 'trigger', 'view') \
               AND name NOT LIKE 'sqlite_%' \
               AND name != 'schema_migrations' \
             ORDER BY \
               CASE type \
                 WHEN 'table'   THEN 1 \
                 WHEN 'view'    THEN 2 \
                 WHEN 'index'   THEN 3 \
                 WHEN 'trigger' THEN 4 \
                 ELSE 5 \
               END, \
               name",
        )
        .context("failed to prepare schema query")?;

    let rows = stmt
        .query_map([], |row| row.get(0))
        .context("failed to query sqlite_master")?;

    let mut statements: Vec<String> = rows
        .collect::<std::result::Result<Vec<_>, _>>()
        .context("failed to read schema rows")?;

    statements.retain(|s| !s.trim().is_empty());
    statements.dedup();

    let with_semicolons: Vec<String> = statements
        .into_iter()
        .map(|s| {
            let trimmed = s.trim_end();
            if trimmed.ends_with(';') {
                trimmed.to_string()
            } else {
                format!("{trimmed};")
            }
        })
        .collect();

    let mut parts = vec![with_semicolons.join("\n\n")];

    for file in files {
        let version = file.version();
        let content = std::fs::read_to_string(&file.path)
            .with_context(|| format!("failed to read migration file: {}", file.path.display()))?;
        let checksum = sha256_hex(content.as_bytes());
        parts.push(format!(
            "INSERT INTO schema_migrations (version, checksum) VALUES ('{version}', '{checksum}');"
        ));
    }

    Ok(parts.join("\n\n"))
}

/// Apply the schema manifest to a fresh database.
///
/// The manifest is a self-contained SQL file that includes both DDL statements
/// and `INSERT INTO schema_migrations` rows. The entire file is executed
/// inside an explicit transaction. Returns the number of migrations recorded
/// (queried from the database after execution).
///
/// Manifests must not contain explicit transaction control (`BEGIN`, `COMMIT`,
/// `ROLLBACK`, savepoints) or transaction-unsafe `PRAGMA`s, because the whole
/// file is wrapped in a single transaction.
///
/// # Errors
///
/// Returns an error if the manifest file is missing, contains no statements, or
/// contains explicit transaction control statements.
pub fn apply_schema_manifest(db: &Db, config: &Config) -> Result<usize> {
    let sql = load_schema_sql(config)?.ok_or_else(|| {
        anyhow::anyhow!(
            "schema manifest not found: {}",
            schema_path(config).display()
        )
    })?;

    let stmts = Parser::parse_sql(&SQLiteDialect {}, &sql).with_context(|| {
        format!(
            "failed to parse schema manifest: {}",
            schema_path(config).display()
        )
    })?;

    if stmts.iter().any(crate::sql::is_transaction_control) {
        return Err(anyhow::anyhow!(
            "schema manifest must not contain explicit transaction control statements: {}",
            schema_path(config).display()
        ));
    }

    if !stmts.iter().any(is_schema_creating_statement) {
        return Err(anyhow::anyhow!(
            "schema manifest has no DDL content: {}",
            schema_path(config).display()
        ));
    }

    // Wrap the generated manifest in an explicit transaction so a failed statement cannot leave partial schema/insert state behind.
    let tx_sql = format!("BEGIN TRANSACTION;\n{sql}\nCOMMIT;");
    match db.connection().execute_batch(&tx_sql) {
        Ok(()) => {}
        Err(e) => {
            if !db.connection().is_autocommit()
                && let Err(rb_err) = db.connection().execute_batch("ROLLBACK;")
            {
                warn!(error = %rb_err, "failed to rollback aborted schema manifest transaction");
            }
            return Err(e).context("failed to execute schema manifest");
        }
    }

    let count: i64 = db
        .connection()
        .query_row("SELECT COUNT(*) FROM schema_migrations", [], |r| r.get(0))
        .context("failed to count applied migrations")?;

    Ok(count as usize)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::db::Db;
    use rusqlite::Connection;
    use tempfile::TempDir;

    fn setup_db() -> Connection {
        let conn = Connection::open_in_memory().unwrap();
        conn.execute_batch(
            "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT NOT NULL);
             CREATE TABLE posts (id INTEGER PRIMARY KEY, title TEXT, user_id INTEGER, FOREIGN KEY(user_id) REFERENCES users(id));
             CREATE INDEX idx_posts_user_id ON posts(user_id);",
        )
        .unwrap();
        conn
    }

    fn write_migration_file(
        dir: &TempDir,
        timestamp: &str,
        slug: &str,
        content: &str,
    ) -> MigrationFile {
        let migrations_dir = dir.path().join("db/migrations");
        std::fs::create_dir_all(&migrations_dir).unwrap();
        let filename = format!("{timestamp}_{slug}.sql");
        let path = migrations_dir.join(&filename);
        std::fs::write(&path, content).unwrap();
        MigrationFile {
            timestamp: timestamp.to_string(),
            slug: slug.to_string(),
            path,
        }
    }

    #[test]
    fn generate_schema_sql_returns_all_ddl() {
        let conn = setup_db();
        let sql = generate_schema_sql(&conn, &[]).unwrap();

        assert!(sql.contains("CREATE TABLE users"));
        assert!(sql.contains("CREATE TABLE posts"));
        assert!(sql.contains("CREATE INDEX idx_posts_user_id"));
    }

    #[test]
    fn generate_schema_sql_excludes_schema_migrations() {
        let conn = setup_db();
        conn.execute_batch(
            "CREATE TABLE schema_migrations (version TEXT PRIMARY KEY, checksum TEXT NOT NULL);",
        )
        .unwrap();

        let sql = generate_schema_sql(&conn, &[]).unwrap();
        assert!(
            !sql.contains("schema_migrations"),
            "schema_migrations should be excluded"
        );
    }

    #[test]
    fn generate_schema_sql_excludes_sqlite_internal() {
        let conn = setup_db();
        let sql = generate_schema_sql(&conn, &[]).unwrap();
        assert!(
            !sql.contains("sqlite_"),
            "internal SQLite objects should be excluded"
        );
    }

    #[test]
    fn generate_schema_sql_empty_database() {
        let conn = Connection::open_in_memory().unwrap();
        let sql = generate_schema_sql(&conn, &[]).unwrap();
        assert!(sql.is_empty());
    }

    #[test]
    fn generate_schema_sql_tables_before_indexes() {
        let conn = setup_db();
        let sql = generate_schema_sql(&conn, &[]).unwrap();

        let table_pos = sql.find("CREATE TABLE users").unwrap();
        let index_pos = sql.find("CREATE INDEX idx_posts_user_id").unwrap();
        assert!(
            table_pos < index_pos,
            "tables must appear before indexes in generated schema"
        );
    }

    #[test]
    fn generate_schema_sql_embeds_migration_inserts() {
        let dir = TempDir::new().unwrap();
        let conn = setup_db();
        conn.execute_batch(
            "CREATE TABLE schema_migrations (version TEXT PRIMARY KEY, checksum TEXT NOT NULL);
             INSERT INTO schema_migrations (version, checksum) VALUES ('20240101000000_alpha', 'abc123');",
        )
        .unwrap();

        let files = vec![write_migration_file(
            &dir,
            "20240101000000",
            "alpha",
            "CREATE TABLE foo (id INTEGER);",
        )];

        let sql = generate_schema_sql(&conn, &files).unwrap();
        assert!(sql.contains("INSERT INTO schema_migrations"));
        assert!(sql.contains("20240101000000_alpha"));
        assert!(sql.contains("checksum"));
    }

    #[test]
    fn apply_schema_manifest_fails_when_missing() {
        let dir = TempDir::new().unwrap();
        let config = Config {
            project_root: dir.path().to_path_buf(),
            schema_path: "db/schema.sql".to_string(),
            database_path: ":memory:".to_string(),
            ..Config::default()
        };

        let db = Db::open(&config).unwrap();

        let result = apply_schema_manifest(&db, &config);
        assert!(result.is_err());
        let err = result.unwrap_err().to_string();
        assert!(err.contains("not found"));
    }

    #[test]
    fn apply_schema_manifest_fails_when_header_only() {
        let dir = TempDir::new().unwrap();
        let config = Config {
            project_root: dir.path().to_path_buf(),
            schema_path: "db/schema.sql".to_string(),
            database_path: ":memory:".to_string(),
            ..Config::default()
        };

        write_schema_sql(&config, "").unwrap();

        let db = Db::open(&config).unwrap();

        let result = apply_schema_manifest(&db, &config);
        assert!(result.is_err());
        let err = result.unwrap_err().to_string();
        assert!(err.contains("no DDL content"));
    }

    #[test]
    fn apply_schema_manifest_fails_when_inserts_only() {
        let dir = TempDir::new().unwrap();
        let config = Config {
            project_root: dir.path().to_path_buf(),
            schema_path: "db/schema.sql".to_string(),
            database_path: ":memory:".to_string(),
            ..Config::default()
        };

        let content = format!(
            "{}\nINSERT INTO schema_migrations (version, checksum) VALUES ('20240101000000_test', 'abc123');",
            HEADER
        );
        std::fs::create_dir_all(dir.path().join("db")).unwrap();
        std::fs::write(schema_path(&config), content).unwrap();

        let db = Db::open(&config).unwrap();
        db.connection().execute_batch(
            "CREATE TABLE schema_migrations (version TEXT PRIMARY KEY, checksum TEXT NOT NULL, applied_at TEXT NOT NULL DEFAULT (datetime('now')));",
        ).unwrap();

        let result = apply_schema_manifest(&db, &config);
        assert!(result.is_err());
        let err = result.unwrap_err().to_string();
        assert!(err.contains("no DDL content"));
    }

    #[test]
    fn apply_schema_manifest_executes_ddl_and_inserts() {
        let dir = TempDir::new().unwrap();
        let config = Config {
            project_root: dir.path().to_path_buf(),
            schema_path: "db/schema.sql".to_string(),
            database_path: ":memory:".to_string(),
            ..Config::default()
        };

        let content = format!(
            "{}\nCREATE TABLE foo (id INTEGER PRIMARY KEY);\n\nINSERT INTO schema_migrations (version, checksum) VALUES ('20240101000000_test', 'abc123');",
            HEADER
        );
        std::fs::create_dir_all(dir.path().join("db")).unwrap();
        std::fs::write(schema_path(&config), content).unwrap();

        let db = Db::open(&config).unwrap();
        db.connection().execute_batch(
            "CREATE TABLE schema_migrations (version TEXT PRIMARY KEY, checksum TEXT NOT NULL, applied_at TEXT NOT NULL DEFAULT (datetime('now')));",
        ).unwrap();

        let count = apply_schema_manifest(&db, &config).unwrap();
        assert_eq!(count, 1);

        let table_count: i64 = db
            .connection()
            .query_row(
                "SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name='foo'",
                [],
                |r| r.get(0),
            )
            .unwrap();
        assert_eq!(table_count, 1);

        let migration_count: i64 = db
            .connection()
            .query_row("SELECT COUNT(*) FROM schema_migrations", [], |r| r.get(0))
            .unwrap();
        assert_eq!(migration_count, 1);
    }

    #[test]
    fn apply_schema_manifest_rolls_back_on_failure() {
        let dir = TempDir::new().unwrap();
        let config = Config {
            project_root: dir.path().to_path_buf(),
            schema_path: "db/schema.sql".to_string(),
            database_path: "app.db".to_string(),
            ..Config::default()
        };

        // Manifest has a successful DDL, a successful insert, then a failing duplicate DDL.
        let content = format!(
            "{}\nCREATE TABLE foo (id INTEGER PRIMARY KEY);\nINSERT INTO schema_migrations (version, checksum) VALUES ('20240101000000_test', 'abc123');\nCREATE TABLE foo (id INTEGER PRIMARY KEY);",
            HEADER
        );
        std::fs::create_dir_all(dir.path().join("db")).unwrap();
        std::fs::write(schema_path(&config), content).unwrap();

        let db = Db::open(&config).unwrap();
        crate::db::ensure_schema_migrations(db.connection()).unwrap();

        let result = apply_schema_manifest(&db, &config);
        assert!(result.is_err(), "duplicate CREATE TABLE should fail");

        // Connection must remain usable after rollback.
        let n: i32 = db
            .connection()
            .query_row("SELECT 1", [], |r| r.get(0))
            .unwrap();
        assert_eq!(n, 1);

        db.close().unwrap();

        // Reopen to verify nothing was persisted to disk.
        let db_path = dir.path().join("app.db");
        let conn = Connection::open(&db_path).unwrap();

        let table_count: i64 = conn
            .query_row(
                "SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name='foo'",
                [],
                |r| r.get(0),
            )
            .unwrap();
        assert_eq!(table_count, 0, "partial DDL must be rolled back");

        let migration_count: i64 = conn
            .query_row("SELECT COUNT(*) FROM schema_migrations", [], |r| r.get(0))
            .unwrap();
        assert_eq!(
            migration_count, 0,
            "partial migration inserts must be rolled back"
        );
    }

    #[test]
    fn apply_schema_manifest_rejects_explicit_transaction_control() {
        let dir = TempDir::new().unwrap();
        let config = Config {
            project_root: dir.path().to_path_buf(),
            schema_path: "db/schema.sql".to_string(),
            database_path: "app.db".to_string(),
            ..Config::default()
        };

        std::fs::create_dir_all(dir.path().join("db")).unwrap();
        for manifest in [
            format!(
                "{}\nBEGIN;\nCREATE TABLE foo (id INTEGER PRIMARY KEY);\nCOMMIT;",
                HEADER
            ),
            format!(
                "{}\nCREATE TABLE foo (id INTEGER PRIMARY KEY);\nROLLBACK;",
                HEADER
            ),
        ] {
            std::fs::write(schema_path(&config), manifest).unwrap();

            let db = Db::open(&config).unwrap();
            let result = apply_schema_manifest(&db, &config);
            assert!(
                result.is_err(),
                "manifest with transaction control should fail"
            );
            let err = result.unwrap_err().to_string();
            assert!(
                err.contains("transaction control"),
                "expected error to mention transaction control, got: {err}"
            );
            db.close().unwrap();
        }
    }

    #[test]
    fn schema_has_content_false_for_block_comments_only() {
        let dir = TempDir::new().unwrap();
        let config = Config {
            project_root: dir.path().to_path_buf(),
            schema_path: "db/schema.sql".to_string(),
            ..Config::default()
        };

        std::fs::create_dir_all(dir.path().join("db")).unwrap();
        let content = format!("{}\n/* some block comment */\n/* another */\n", HEADER);
        std::fs::write(schema_path(&config), content).unwrap();

        assert!(!schema_has_content(&config));
    }

    #[test]
    fn schema_has_content_true_for_actual_ddl() {
        let dir = TempDir::new().unwrap();
        let config = Config {
            project_root: dir.path().to_path_buf(),
            schema_path: "db/schema.sql".to_string(),
            ..Config::default()
        };

        std::fs::create_dir_all(dir.path().join("db")).unwrap();
        let content = format!("{}\nCREATE TABLE foo (id INTEGER);\n", HEADER);
        std::fs::write(schema_path(&config), content).unwrap();

        assert!(schema_has_content(&config));
    }

    #[test]
    fn schema_has_content_false_for_inserts_only() {
        let dir = TempDir::new().unwrap();
        let config = Config {
            project_root: dir.path().to_path_buf(),
            schema_path: "db/schema.sql".to_string(),
            ..Config::default()
        };

        std::fs::create_dir_all(dir.path().join("db")).unwrap();
        let content = format!(
            "{}\nINSERT INTO schema_migrations (version, checksum) VALUES ('20240101000000_alpha', 'abc');",
            HEADER
        );
        std::fs::write(schema_path(&config), content).unwrap();

        assert!(
            !schema_has_content(&config),
            "INSERT-only manifest should not count as having DDL content"
        );
    }

    #[test]
    fn schema_version_extracts_latest() {
        let dir = TempDir::new().unwrap();
        let config = Config {
            project_root: dir.path().to_path_buf(),
            schema_path: "db/schema.sql".to_string(),
            ..Config::default()
        };

        let content = format!(
            "{}\nCREATE TABLE foo (id INTEGER);\n\nINSERT INTO schema_migrations (version, checksum) VALUES ('20240101000000_alpha', 'abc');\nINSERT INTO schema_migrations (version, checksum) VALUES ('20240102000000_beta', 'def');",
            HEADER
        );
        std::fs::create_dir_all(dir.path().join("db")).unwrap();
        std::fs::write(schema_path(&config), content).unwrap();

        let version = schema_version(&config).unwrap().unwrap();
        assert_eq!(version, "20240102000000_beta");
    }

    #[test]
    fn schema_version_tracks_max_not_last() {
        let dir = TempDir::new().unwrap();
        let config = Config {
            project_root: dir.path().to_path_buf(),
            schema_path: "db/schema.sql".to_string(),
            ..Config::default()
        };

        let content = format!(
            "{}\nCREATE TABLE foo (id INTEGER);\n\nINSERT INTO schema_migrations (version, checksum) VALUES ('20240103000000_gamma', 'ghi');\nINSERT INTO schema_migrations (version, checksum) VALUES ('20240101000000_alpha', 'abc');\nINSERT INTO schema_migrations (version, checksum) VALUES ('20240102000000_beta', 'def');",
            HEADER
        );
        std::fs::create_dir_all(dir.path().join("db")).unwrap();
        std::fs::write(schema_path(&config), content).unwrap();

        let version = schema_version(&config).unwrap().unwrap();
        assert_eq!(version, "20240103000000_gamma");
    }

    #[test]
    fn schema_version_handles_multi_row_values() {
        let dir = TempDir::new().unwrap();
        let config = Config {
            project_root: dir.path().to_path_buf(),
            schema_path: "db/schema.sql".to_string(),
            ..Config::default()
        };

        let content = format!(
            "{}\nCREATE TABLE foo (id INTEGER);\n\nINSERT INTO schema_migrations (version, checksum) VALUES ('20240101000000_alpha', 'abc'), ('20240103000000_gamma', 'ghi'), ('20240102000000_beta', 'def');",
            HEADER
        );
        std::fs::create_dir_all(dir.path().join("db")).unwrap();
        std::fs::write(schema_path(&config), content).unwrap();

        let version = schema_version(&config).unwrap().unwrap();
        assert_eq!(version, "20240103000000_gamma");
    }

    #[test]
    fn schema_version_returns_none_when_no_inserts() {
        let dir = TempDir::new().unwrap();
        let config = Config {
            project_root: dir.path().to_path_buf(),
            schema_path: "db/schema.sql".to_string(),
            ..Config::default()
        };

        let content = format!("{}\nCREATE TABLE foo (id INTEGER);\n", HEADER);
        std::fs::create_dir_all(dir.path().join("db")).unwrap();
        std::fs::write(schema_path(&config), content).unwrap();

        assert!(schema_version(&config).unwrap().is_none());
    }

    #[test]
    fn schema_is_fresh_true_when_up_to_date() {
        let dir = TempDir::new().unwrap();
        let config = Config {
            project_root: dir.path().to_path_buf(),
            schema_path: "db/schema.sql".to_string(),
            ..Config::default()
        };

        let content = format!(
            "{}\nCREATE TABLE foo (id INTEGER);\n\nINSERT INTO schema_migrations (version, checksum) VALUES ('20240102000000_beta', 'abc');",
            HEADER
        );
        std::fs::create_dir_all(dir.path().join("db")).unwrap();
        std::fs::write(schema_path(&config), content).unwrap();

        let files = vec![
            write_migration_file(&dir, "20240101000000", "alpha", "SELECT 1;"),
            write_migration_file(&dir, "20240102000000", "beta", "SELECT 2;"),
        ];

        assert!(schema_is_fresh(&config, &files));
    }

    #[test]
    fn schema_is_fresh_false_when_stale() {
        let dir = TempDir::new().unwrap();
        let config = Config {
            project_root: dir.path().to_path_buf(),
            schema_path: "db/schema.sql".to_string(),
            ..Config::default()
        };

        let content = format!(
            "{}\nCREATE TABLE foo (id INTEGER);\n\nINSERT INTO schema_migrations (version, checksum) VALUES ('20240101000000_alpha', 'abc');",
            HEADER
        );
        std::fs::create_dir_all(dir.path().join("db")).unwrap();
        std::fs::write(schema_path(&config), content).unwrap();

        let files = vec![
            write_migration_file(&dir, "20240101000000", "alpha", "SELECT 1;"),
            write_migration_file(&dir, "20240102000000", "beta", "SELECT 2;"),
        ];

        assert!(!schema_is_fresh(&config, &files));
    }

    #[test]
    fn write_and_load_round_trip() {
        let dir = TempDir::new().unwrap();
        let config = Config {
            project_root: dir.path().to_path_buf(),
            schema_path: "db/schema.sql".to_string(),
            ..Config::default()
        };

        let sql = "CREATE TABLE test (id INTEGER);";
        write_schema_sql(&config, sql).unwrap();

        let loaded = load_schema_sql(&config).unwrap().unwrap();
        assert!(loaded.starts_with(HEADER));
        assert!(loaded.contains("CREATE TABLE test"));
    }

    #[test]
    fn load_schema_sql_returns_none_when_missing() {
        let dir = TempDir::new().unwrap();
        let config = Config {
            project_root: dir.path().to_path_buf(),
            schema_path: "db/schema.sql".to_string(),
            ..Config::default()
        };

        assert!(load_schema_sql(&config).unwrap().is_none());
    }

    #[test]
    fn schema_exists_returns_false_when_missing() {
        let dir = TempDir::new().unwrap();
        let config = Config {
            project_root: dir.path().to_path_buf(),
            schema_path: "db/schema.sql".to_string(),
            ..Config::default()
        };

        assert!(!schema_exists(&config));
    }

    #[test]
    fn schema_exists_returns_true_when_present() {
        let dir = TempDir::new().unwrap();
        let config = Config {
            project_root: dir.path().to_path_buf(),
            schema_path: "db/schema.sql".to_string(),
            ..Config::default()
        };

        write_schema_sql(&config, "SELECT 1;").unwrap();
        assert!(schema_exists(&config));
    }

    #[test]
    fn write_schema_sql_creates_parent_directory() {
        let dir = TempDir::new().unwrap();
        let config = Config {
            project_root: dir.path().to_path_buf(),
            schema_path: "deep/nested/dir/schema.sql".to_string(),
            ..Config::default()
        };

        write_schema_sql(&config, "SELECT 1;").unwrap();
        assert!(schema_exists(&config));
    }

    #[test]
    fn write_schema_sql_empty_sql_writes_header_only() {
        let dir = TempDir::new().unwrap();
        let config = Config {
            project_root: dir.path().to_path_buf(),
            schema_path: "db/schema.sql".to_string(),
            ..Config::default()
        };

        write_schema_sql(&config, "").unwrap();
        let loaded = load_schema_sql(&config).unwrap().unwrap();
        assert_eq!(loaded, HEADER);
    }
}
